### Table List
GET {{host}}/book_reply_action?page=1&limit=10
Authorization: {{token}}

### Table Item
GET {{host}}/book_reply_action/1
Authorization: {{token}}

### Table Create
POST {{host}}/book_reply_action
Authorization: {{token}}
Content-Type: application/json



### Table Update
PUT {{host}}/book_reply_action/1
Authorization: {{token}}
Content-Type: application/json



### Table Delete
DELETE {{host}}/book_reply_action/1
Authorization: {{token}}

### EXPORT 
POST {{host}}/book_reply_action/export
Authorization: {{token}}
Content-Type: application/json

{}