
### Get Book List
GET  {{host}}/book
Authorization: {{token}}

### Get Book by ID
GET  {{host}}/book/6
Authorization: {{token}}

### POST Book
POST {{host}}/book
Content-Type: application/json
Authorization: {{token}}

{
  "name": "Book",
  "category_id" : 7,
  "author_id": 4
}

### PUT Book
PUT  {{host}}/book/7
Content-Type: application/json
Authorization: {{token}}

{
  "name": "Book Name 2",
  "category_id": 1
}

### DELETE Book
DELETE  {{host}}/book/8
Authorization: {{token}}

### GET Book Chapters By ID
GET  {{host}}/book/6/chapters
Authorization: {{token}}

### POST Crawl Book
GET {{host}}/book/1/startCrawl
Authorization: {{token}}

### GET Dicationaryy all
GET {{host}}/book/all
Authorization: {{token}}

### GET Book Comments
GET {{host}}/book/1/comments
Authorization: {{token}}

### EXPORT 
POST {{host}}/book/export
Authorization: {{token}}
Content-Type: application/json

{}

### API Book All
GET {{host}}/api/book/all

### API Book Chapters With BookID
GET {{host}}/api/book/1/chapters
