
### GET Category
GET {{host}}/category
Authorization: {{token}}


### GET Category Info
GET {{host}}/category/1
Authorization: {{token}}


### Category Create
POST {{host}}/category
Authorization: {{token}}
Content-Type: application/json

{
  "name": "玄幻类",
  "identify": "xuanhuan",
  "remark": ""
}

### Update Category
PUT {{host}}/category/1
Authorization: {{token}}
Content-Type: application/json

{
  "name": "科幻类-更新",
  "identify": "technology",
  "remark": "这是科幻类备注"
}

### DELETE Category
DELETE {{host}}/category/1
Authorization: {{token}}

### GET all
GET {{host}}/category/all
Authorization: {{token}}

### EXPORT 
POST {{host}}/category/export
Authorization: {{token}}
Content-Type: application/json

{}

### EXTERNAL GET LIST
GET {{host}}/api/category

### EXTERNAL GET Books With CategoryID
GET {{host}}/api/category/1/books
