### GET Dictionary
GET {{host}}/dictionary
Authorization: {{token}}


### GET Dictionary by ID
GET {{host}}/dictionary/4
Authorization: {{token}}

### Create Dictionary
POST {{host}}/dictionary
Authorization: {{token}}
Content-Type: application/json

{
  "name": "主题",
  "identify": "theme",
  "status": 1,
  "remark": ""
}

### Update Dictionary
PUT {{host}}/dictionary/1
Authorization: {{token}}
Content-Type: application/json

{
  "name": "testupdate",
  "identify": "test",
  "status": 1,
  "remark": "test remark update"
}

### DELETE
DELETE {{host}}/dictionary/1
Authorization: {{token}}

### GET Dictionary Data List
GET {{host}}/dictionary/4/dict_data
Authorization: {{token}}

### GET Dicationaryy all
GET {{host}}/dictionary/all
Authorization: {{token}}
