
### Role List
GET {{host}}/role?page=1&limit=1
Authorization: {{token}}


### Role Info
GET {{host}}/role/1
Authorization: {{token}}

### Role Create
POST {{host}}/role
Authorization: {{token}}
Content-Type: application/json

{
  "name": "admin",
  "authorities": "1,2"
}

### Role Update
PUT  {{host}}/role/6
Content-Type: application/json
Authorization: {{token}}

{
  "name": "admin",
  "authorities": "[1,2,3]"
}

### DELETE
DELETE  {{host}}/role/6
Authorization: {{token}}

### GET all
GET {{host}}/role/all
Authorization: {{token}}


### EXPORT 
POST {{host}}/role/export
Authorization: {{token}}
Content-Type: application/json

{}

### POST Bind Menus
POST {{host}}/role/1/bind_menus
Authorization: {{token}}
Content-Type: application/json

{
  "ids": [1,2,3,4,5,6]
}